development:
  adapter: mysql
  encoding: utf8
  database: quizzr
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: quizzr_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: quizzrdb
  username: quizzrdb
  password: divinopastor30
  host: db.quizzr.net